# Generated by Django 4.2.11 on 2024-03-21 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jenkins_statistics', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='build',
            unique_together={('job', 'build_number')},
        ),
    ]
