# Generated by Django 4.2.11 on 2024-03-21 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jenkins_statistics', '0002_alter_build_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='build',
            old_name='job',
            new_name='job_id',
        ),
        migrations.RenameField(
            model_name='jobresults',
            old_name='build',
            new_name='build_id',
        ),
        migrations.RenameField(
            model_name='jobresults',
            old_name='job',
            new_name='job_id',
        ),
        migrations.AlterUniqueTogether(
            name='build',
            unique_together={('job_id', 'build_number')},
        ),
    ]
