# Generated by Django 4.2.11 on 2024-03-21 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jenkins_statistics', '0003_rename_job_build_job_id_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='jobresults',
            unique_together={('job_id', 'build_id')},
        ),
    ]
